export default {
    showDrawer:false,
    tagList:{
        type:'div',
        pid:null,
        key:'0',
        dataName:'总容器',
        iconName:'icondiv',
        style:{},
        props:{},
        children:[
            {
                type:'div',
                pid:'0',
                key:'0-0',
                dataName:'新建div',
                iconName:'icondiv',
                content:'我是新建div的内容',
                style:{color:'#b10100',fontFamily:'幼圆'},
                props:{},
                children:[
                    {
                        type:'p',
                        pid:'0-0',
                        key:'0-0-0',
                        dataName:'新建p',
                        iconName:'iconp',
                        style:{},
                        props:{},
                        children:[]
                    }
                ]
            },
            {
                type:'div',
                pid:'0',
                key:'0-2',
                dataName:'新建div',
                iconName:'icondiv',
                style:{},
                props:{},
                children:[
                    {
                        type:'p',
                        pid:'0-2',
                        key:'0-2-0',
                        dataName:'新建段落2',
                        iconName:'iconp',
                        content:'我是新建段落2的内容',
                        style:{color:'#ff0000',fontSize:'28px'},
                        props:{},
                        children:[]
                    }
                ]
            },
            {
                type:'div',
                pid:'0',
                key:'0-1',
                dataName:'新建div',
                iconName:'icondiv',
                style:{},
                props:{},
                children:[]
            }
        ]
    },
    selectedTag:{},
    hoveredTagKey:'',       //在树结构上hover的元素的key值，用于与content部分选中样式搭配

}
